#!/usr/bin/env bash

set -e

script/bootstrap

# Ensure that we are running this from the root of the project. If the script is
# run from anywhere else, files can end up in the wrong spot.
echo "---> Running test suite setup checks"
if [[ ! -f "Gemfile" ]] ; then
  echo "     Test suite is not being run from the project root."
  echo "     Please change to the root and re-run the test suite."
  exit 1
fi
echo "---> Pre-checks all passed"
