#!/usr/bin/env bash

set -e

# Handy indentation function to line it all up.
indent() {
  sed "s/^/     /"
}

# Ensure that we are running this from the root of the project. If the script is
# run from anywhere else, files can end up in the wrong spot.
echo "---> Running setup checks"
if [[ ! -f "Gemfile" ]] ; then
  echo "     Test suite is not being run from the project root."
  echo "     Please change to the root and re-run the test suite."
  exit 1
fi
echo "---> Pre-checks all passed"

# Bundle it all up.
echo "---> Fetching all dependencies"
bundle install | indent
echo "---> Bundling completed"

# Run the test suite.
echo "---> Starting test suite"
bundle exec rspec spec --format documentation | indent
echo "---> Test suite completed"